name: bump-chainner-cask
on:
  schedule:
    - cron:  '0 8,20 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        token: ${{secrets.BUMP_CASK_TOKEN}}
        tap: chaiNNer-org/homebrew-chaiNNer
        cask: chainner
        livecheck: true
        dryrun: false
